[[redirects]]
  from = "https://drumnickydrum-sequencer.herokuapp.com/*"
  to = "https://drumnickydrum-sequencer.herokuapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/"
  status = 200